### PR TITLE
Setting babel target to node 8.9

### PR DESCRIPTION
**Pull request by andre-lima**

### CODE REVIEW

**Comment by GuillaumeCz** [comment]
Hello André ! ;) 
Base your work on the develop branch instead of the master one to make the merge possible.
Travis noticed problems, can you look a it ? ;)

**Comment by andre-lima** [comment]
The Travis CI build is failing on the Nodejs 4 verification, which would make sense due to the fact that babel is targeting node 8 now.

**Comment by GuillaumeCz** [comment]
Do you think that we can remove the NodeJs 4.0 mention from the .travis.yml in order to validate all the tests ?

**Comment by andre-lima** [comment]
Good idea. Build is passing now!

**Review by GuillaumeCz — APPROVED** [review]

**Pull request merged**
